<?php
namespace Neos\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * The migration to move names from edges to nodes and add a removed flag to nodes
 */
class Version20170223215730 extends AbstractMigration
{

    /**
     * @return string
     */
    public function getDescription()
    {
        return '';
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');

        $this->addSql('ALTER TABLE neos_contentrepository_projection_hierarchyedge DROP COLUMN name');
        $this->addSql('ALTER TABLE neos_contentrepository_projection_node ADD name VARCHAR(255) NULL, ADD removed BOOLEAN NOT NULL');
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');

        $this->addSql('ALTER TABLE neos_contentrepository_projection_hierarchyedge ADD name VARCHAR(255) NULL');
        $this->addSql('ALTER TABLE neos_contentrepository_projection_node DROP COLUMN name, DROP COLUMN removed');
    }
}
