<?php
namespace Neos\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs! This block will be used as the migration description if getDescription() is not used.
 */
class Version20170222112520 extends AbstractMigration
{

    /**
     * @return string
     */
    public function getDescription()
    {
        return '';
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');

        $this->addSql('CREATE TABLE neos_contentrepository_projection_hierarchyedge (parentnodesidentifieringraph VARCHAR(255) NOT NULL, subgraphidentifier VARCHAR(255) NOT NULL, childnodesidentifieringraph VARCHAR(255) NOT NULL, name VARCHAR(255) NULL, position INT NOT NULL, PRIMARY KEY(parentnodesidentifieringraph, subgraphidentifier, childnodesidentifieringraph)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE neos_contentrepository_projection_node (identifieringraph VARCHAR(255) NOT NULL, identifierinsubgraph VARCHAR(255) NOT NULL, subgraphidentifier VARCHAR(255) NOT NULL, properties LONGTEXT NOT NULL COMMENT \'(DC2Type:flow_json_array)\', nodetypename VARCHAR(255) NOT NULL, PRIMARY KEY(identifieringraph)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');

        $this->addSql('DROP TABLE neos_contentrepository_projection_hierarchyedge');
        $this->addSql('DROP TABLE neos_contentrepository_projection_node');
    }
}
